#include "CppInitTemplateProvider.h"
#include <sstream>

namespace topo::lang {

// The C++ native-lldb formatter script, embedded at
// configure time from topo-lang-cpp/topo-debug/lldb_formatter.py via the
// generated CppLldbFormatterAsset.cpp (CMake configure_file). Declared
// extern so the multi-hundred-line raw string lives in its own TU and the
// provider stays readable.
extern const char kCppLldbFormatterScript[];

std::string CppInitTemplateProvider::generateTopoToml(const std::string& projectName) const {
    std::ostringstream out;
    out << "[project]\n"
        << "name = \"" << projectName << "\"\n\n"
        << "[topo]\n"
        << "root = \"topo/main.topo\"\n\n"
        << "[build]\n"
        << "language = \"cpp\"\n"
        << "sources = [\"src/**/*.cpp\"]\n"
        << "output = \"" << projectName << "\"\n\n"
        << "[completeness]\n"
        << "ignore_main = true\n";
    return out.str();
}

std::string CppInitTemplateProvider::generateTypeBindings() const {
    return "using int = std::cpp17::int;\n"
           "using bool = std::cpp17::bool;\n"
           "using float = std::cpp17::float;\n"
           "using double = std::cpp17::double;\n"
           "using size_t = std::cpp17::size_t;\n";
}

std::string CppInitTemplateProvider::lldbFormatterRelPath() const {
    return "topo/lldb_formatter.py";
}

std::string CppInitTemplateProvider::lldbFormatterScript() const {
    return kCppLldbFormatterScript;
}

std::string CppInitTemplateProvider::generateLldbInit(
    const std::string& formatterRelPath) const {
    std::ostringstream out;
    out << "# Generated by `topo init` — native-lldb formatter "
           "(zero-install).\n"
        << "#\n"
        << "# Sourced automatically when you run `lldb ./" /* hint */
           "<your-binary>` from\n"
        << "# this directory. It teaches lldb to show the *logical declared "
           "view*\n"
        << "# of a Topo-optimized variable (read from the sibling "
           "*.topo-dbg.json\n"
        << "# that `topo build` emits) instead of the raw post-transform "
           "layout.\n"
        << "#\n"
        << "# Safe to delete or edit; absence just falls back to default "
           "lldb\n"
        << "# formatting. lldb must be built with Python scripting for this "
           "to\n"
        << "# take effect.\n"
        << "command script import " << formatterRelPath << "\n";
    return out.str();
}

} // namespace topo::lang
