#ifndef TOPO_APP_EMIT_H
#define TOPO_APP_EMIT_H

// @stability provisional
// User-facing emission API. The deterministic Graph -> .topo mapping
// is intended to settle to `stable` once the round-trip fidelity
// matrix is complete; today it remains provisional.

// Graph -> .topo emission.
//
// This is the deterministic mapping the proposal commits to
// ("deterministic rules for producing the .topo, not black-magic
// inference"), not inference:
//
//   - handler A's output feeds handler B's input  -> edge A -> B
//   - logic chain A -> B -> C                      -> flow with edges
//   - the flow's stage topology is left to core PipelineAnalysis; the
//     emitter only states edges, never stage numbers (handler/flow spec:
//     flow body accepts pipeline edges only).
//
// The output is human-readable and hand-editable by construction — that
// is the proposal's decisive round-trip constraint, so the emitter
// favours a stable, obvious layout over compactness. Byte-for-byte the
// same shape as the Python reference's _emit.py, the only host-specific
// difference being the scalar-alias preamble: the Python host aliases
// std::python::*, the C++ host aliases std::cpp17::* — exactly the
// vocabulary CppInitTemplateProvider::generateTypeBindings() emits, so
// emitted .topo consumes the same stdlib the rest of the C++ toolchain
// expects.

#include <string>

#include <topo/app_model.h>

namespace topo::app {

// Scalar aliases the C++ host binds. std::cpp17::* matches the C++
// topo-init preamble; `str` is added here because a handler may take a
// string input even though the default topo-init binding set omits it
// (the parser accepts it as a plain using-alias target — verified
// against the fresh grammar).
inline constexpr const char* kPreamble =
    "using int = std::cpp17::int;\n"
    "using float = std::cpp17::float;\n"
    "using bool = std::cpp17::bool;\n"
    "using str = std::cpp17::str;";

inline std::string emit_topo(const Graph& graph) {
    std::string out;
    out += "// Generated by topo-app (C++). Human-readable and round-trip\n";
    out += "// safe: editing this file and reading it back yields the same\n";
    out += "// logic graph. Hand edits survive; this is a view, not an IR.\n";
    out += "\n";
    out += kPreamble;
    out += "\n\n";
    out += "namespace " + graph.namespace_name() + " {\n";
    out += "  public:\n";
    for (const auto& h : graph.handlers())
        out += "    " + h.signature() + "\n";
    if (graph.has_flow()) {
        out += "\n";
        out += "    flow " + graph.flow().name + " {\n";
        for (const auto& e : graph.flow().edges) {
            std::string tgt = e.is_terminal() ? "void" : *e.target;
            out += "      " + e.source + " -> " + tgt + ";\n";
        }
        out += "    }\n";
    }
    out += "}\n";
    return out;
}

}  // namespace topo::app

#endif  // TOPO_APP_EMIT_H
